---
title: "Reading List"
author: Samantha Toet & Michele Claibourn, [The Equity Center](https://www.virginiaequitycenter.org/)
date: "Last updated: 9/11/2024"
output: 
  html_document:
    toc: true
    toc_float: true
---

An ongoing collection of background reading materials pertaining to equitable gun violence research and how it can be applied to the Charlottesville and Albemarle region.

## Local Information

-   [UVA President's Council Community Safety Working Group Report](https://prescouncil.president.virginia.edu/sites/g/files/jsddwu616/files/2024-01/Final%20Community%20Safety%20Working%20Group%20Report_24.pdf), Equity Center, 2023

-   [Charlottesville City Health Dashboard](https://www.cityhealthdashboard.com/VA/Charlottesville/city-overview), Congressional District Health Dashboard, 2023

- [Our Kids are Dying: Gun Violence Again Spikes in Charlottesville](https://www.cvilletomorrow.org/newsletter/our-kids-are-dying-gun-violence-again-spikes-in-charlottesville/), Cville Tomorrow, 2022

- [Shots Heard Round the City: Police, Community Look for Solutions to Stop Gun Violence ](https://www.c-ville.com/shots-heard-round-the-city), Cville Weekly, 2023 


## National Studies

-   [Firearm Violence: A Public Health Crisis in America](https://www.hhs.gov/sites/default/files/firearm-violence-advisory.pdf), US Surgeon General's Advisory, 2024

-   [What the Data Says about Gun Deaths in the US](https://www.pewresearch.org/short-reads/2023/04/26/what-the-data-says-about-gun-deaths-in-the-u-s/), PEW Research, 2023

-   [Social determinants of health in relation to firearm-related homicides in the United States: A nationwide multilevel cross-sectional study](https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1002978), PLOS Medicine, 2019

- [Gun Violence: The Impact on Society](https://nihcm.org/publications/gun-violence-the-impact-on-society), National Institute for Health Care Management, 2024


## Research Infrastructure

-   [Structural Competency and the Future of Firearm Research](https://www.sciencedirect.com/science/article/pii/S0277953621002112), Social Science and Medicine, 2021

-   [Racial Equity Impact Assessment Tool for Gun Violence Prevention](https://efsgv.org/wp-content/uploads/WEST_EFSGV_REIA_012275.pdf), the Educational Fund to Stop Gun Violence, 2022

-   [Centering Racial Equity Throughout Data Integration](https://aisp.upenn.edu/wp-content/uploads/2022/07/AISP-Toolkit_5.27.20.pdf), Actionable Intelligence for Social Policy, 2020

-   [Firearm Availability, Homicide, and the Context of Structural Disadvantage](https://journals.sagepub.com/doi/10.1177/10887679211043806), Sage Journals, 2023


## Community Engagement

- [Fostering Partnerships for Community Engagement](https://www.urban.org/sites/default/files/publication/104935/fostering-partnerships-for-community-engagement_0.pdf), Urban Institute, 2021

- [Community Safety as a Social Determinant of Health](https://nap.nationalacademies.org/read/27741/chapter/1), National Academies of Sciences, Engineering, and Medicine, 2024



## Youth and Adolescents

-   [Trauma recidivism is pervasive and is associated with mental and social health opportunities](https://www.sciencedirect.com/science/article/pii/S0020138322008063), Injury, 2023

-   [Firearm Injuries In Children And Adolescents: Health And Economic Consequences Among Survivors And Family Members](https://www.healthaffairs.org/doi/10.1377/hlthaff.2023.00587), Health Affairs, 2023

-   [The Impact of Gun Violence on Children and Adolescents](https://www.kff.org/mental-health/issue-brief/the-impact-of-gun-violence-on-children-and-adolescents), KFF, 2024
